### ISSUE TITLE
Disable CRC reading for faster processing

### ISSUE THREAD

**Issue by xmedeko** [polyvertex/fitdecode#1]
I would like to have an option to disable CRC check completely to speed up processing of the large FITs. I.e. some three state enum: DISABLED, READ-ONLY, ENABLED.

Note: the FIT SDK does not report CRC errors by default. (I.e. something like READ-ONLY in the above enum.)

**Comment by polyvertex** [comment]
Oops I just rolled out a new release without this. Completely forgot. Sorry for that :(
PR are welcome if you feel like it and happen to use this library...
