### ISSUE TITLE
Question: how does fitdecode decode the binary file?

### ISSUE THREAD

**Issue by johncalab** [polyvertex/fitdecode#11]
First off, thanks a lot for creating this!

Not an issue, I would just like to understand better how this whole thing works. I was reading through the source code to try and understand how on earth you are able to parse a binary file. So far I've found only the compute_crc function in utils. 

Question1: is this the bit that does all the heavylifting when it comes to parsing the binary?

Question2: where do the values in the CRC_TABLE constant come from?

**Comment by polyvertex** [comment]
Your questions are more related to the Python programming language and the FIT file format, than the fitdecode library itself. Besides it would take a tremendous amount of time for someone to answer them. Sorry I cannot help with that.
