### ISSUE TITLE
Could you provide examples on the docs?

### ISSUE THREAD

**Issue by oculos** [polyvertex/fitdecode#12]
Hi,

Thank you very much for fitdecode! Really nice!
I wonder if you could provide some examples to make it easy to understand how to use it. It took me a while to understand a bit how it works - which I do now - to have typical things people might want to do, like having a personal archival system for their workouts.

But one thing I still don't understand is how to use the processors. Can you give an example on how to use them, like for example changing the distance from m to km, or the speed from m/s to km/h? 

Best,

Francis

**Comment by polyvertex** [comment]
Best examples you can find remain the processor classes from the `processors.py` module. The docstring of `DataProcessorBase` explains how it is invoked by `FitReader`. So if you need more details than the ones already provided, you probably want to check out `FitReader`'s code.

However do note that *fitdecode* features are closely related to the FIT file format itself. Therefore there is a point in your journey where you will probably want to dig more in format's official documentation if you go that far.

**Comment by inonoob** [comment]
Hey oculos, maybe if you wanna have a little introduction into the FIT file format, you may wanna check my github repo for a FIT project I'm working one: 

https://github.com/inonoob/Coxswain2Fit 

I try to explain how the Garmin FIT file is build

**Comment by renschler** [comment]
Examples would be lovely. If I figure out more how this library works I'll try to post some.

I've gone through the FIT protocol and still a little overwhelmed. 

```python
with fitdecode.FitReader(src_file) as fit:
    for frame in fit:
        if isinstance(frame, fitdecode.FitDataMessage):
            if (frame.name == "session"):
                 # How would I hex dump the entire session data message?
                 # How would I hex dump an individual field in this message?
```

**Comment by inonoob** [comment]
Hey,

have you download the Garmin SDK ? if you go into the java folder and have java installed you can decode the FIT file which results in a csv file. You can do the changes and re-encode it to a FIT file. 

`pi@raspberrypi:~/Prog/java $  java -jar FitCSVTool.jar -h 
`
`FIT CSV Tool - Protocol 2.0 Profile 21.40 Release
Usage: java -jar FitCSVTool.jar <options> <file>
      -b <FIT FILE> <CSV FILE>  FIT binary to CSV.
      -c <CSV FILE> <FIT FILE>  CSV to FIT binary.`


If you wanna hexdump a FIT file in LINUX: 
`hexdump -C xxxxx.fit`

This helped me to more understand the FIT format
