### ISSUE TITLE
Fit parsing error

### ISSUE THREAD

**Issue by Kypaz** [polyvertex/fitdecode#13]
Hello, I have a fit reading problem (the file is attached)

`FIT parsing error @ 235: invalid field size 1 for type uint32 (expected a multiple of 4)`

I have the problem with 0.7 or 0.6

The supposed FIT SDK version of the file is 20.63.0 (told by supplier of fit file)

I imported succesfully this fit file in Garmin Connect so this is not a corrupted file

Can you help me?

Best regards,

Alexandre [Bouquet]
[fit_error.fit.zip](https://github.com/polyvertex/fitdecode/files/5342018/fit_error.fit.zip)

**Comment by Kypaz** [comment]
Any idea?

Best,
Alexandre

**Comment by polyvertex** [comment]
Do you happen to know the device model that generated the file initially? Note that sometimes it can be found in the fit file itself.

**Comment by Kypaz** [comment]
Hello,

The model is the COROS VERTIX

But I have asked the supplied, I cannot read the file at all with fitdecode, it crashes too early

Thank your for your help

**Comment by Kypaz** [comment]
Any update?

**Comment by inonoob** [comment]
@Kypaz: 
I've tried your file and it is working with the Garmin SDK FIT CSV Tool - Protocol 2.0 Profile 21.40 Release. I can decode it, open the csv and re-encode it. So It must be the lib from what I have checked.

**Comment by mastermaeg** [comment]
Hi
I got the same error with a fit file from Coros Pace 2. 
I guess https://github.com/dtcooper/python-fitparse/pull/116 would also fix this here?

**Comment by polyvertex** [comment]
> I've tried your file and it is working with the Garmin SDK FIT CSV Tool - Protocol 2.0 Profile 21.40 Release. I can decode it, open the csv and re-encode it. So It must be the lib from what I have checked.

FYI SDK's tool seems to skip *unknown* types/fields, such that it goes silent about this kind of errors, whereas both *fitdecode* and *fitparse* libraries intend to dig into types definitions. So that they parse FIT data in a stricter way, not permissive with malformed files.

I will add an option flag to enable a more permissive parsing when possible.

**Comment by Victorivus** [comment]
Had this error when installing with `pip install` , maybe the package on pypi could be updated :)
