### ISSUE TITLE
Test for valid Fit file

### ISSUE THREAD

**Issue by hugokernel** [polyvertex/fitdecode#5]
Hi,
I'm looking for a simple and reliable way to test if a file is a valid fit file, any ideas?
Thx

**Comment by polyvertex** [comment]
As an end-user, you can just use either fitdecode's fitjson or fittxt utility, **without** using the `--nocrc` option.

Or, as a developer using this library, simply iterating through the FIT file as shown in the *Usage Example* of the README file is a good way to check if your file is valid both at reading (CRC) and decoding steps (frames, fields, values, ...). Just stick to the default arguments of the `fitdecode.FitReader` constructor (especially `check_crc` in your case, which must be `ENABLED`):

```python
import fitdecode

with fitdecode.FitReader(src_file, processor=fitdecode.StandardUnitsDataProcessor()) as fit:
    for frame in fit:
        pass
```

The `processor` argument is just an extra check and is not compulsory. It will make **all parts** of fitdecode's decoding features involved in the process so to ensure fitdecode does well with a specific file. Which validates more the library itself than the file but may also extend the triggering of potential issues sooner. So it's still good to have it.

Also, note that both fitjson and fittxt utilities makes use of `StandardUnitsDataProcessor`.

**Comment by hugokernel** [comment]
Great, thx for your answer.

**Comment by polyvertex** [comment]
Closing this then !
