### ISSUE TITLE
Ability to write FIT files (question only)

### ISSUE THREAD

**Issue by slater1** [polyvertex/fitdecode#7]
Hi Jean-Charles, nice work here. I was about to clone python-fitparse and port it to python3 when I discovered your project. Do you have any ambitions to add write support? Would you accept pulls for that? My use case is to add FIT support to [tcxmill](https://github.com/slater1/tcxmill/), a tool I wrote to clean up noisy treadmill data and which obviously only supports tcx at the moment.

**Comment by polyvertex** [comment]
> Do you have any ambitions to add write support?

I am afraid I do not. The FIT format is awful enough to work with and so badly specified, that I do not feel the urge of having to support write operation :(
